### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by cantrowitz** [ddohler/moshpytt#2]
```
moshpytt-dist [redacted]$ python moshpytt.py
Traceback (most recent call last):
  File "moshpytt.py", line 1370, in <module>
    main()
  File "moshpytt.py", line 50, in main
    MoshPyTT(opts)
  File "moshpytt.py", line 1355, in __init__
    self.setup_widgets()
  File "moshpytt.py", line 1188, in setup_widgets
    self.setup_icons()
  File "moshpytt.py", line 1165, in setup_icons
    iconPixBuf16 = gtk.gdk.pixbuf_new_from_file(iconFilename)
glib.GError: Couldn't recognize the image file format for file '[redacted]/moshpytt-dist/icons/moshpytt-logo-16.svg'
```

**Comment by ddohler** [comment]
It looks like it is having trouble opening one of its icon files; it's possible that you are missing a library that provides SVG support, but beyond that, I'm not really sure since I'm not the original author. I was going to suggest that you ask the original author, but it appears that the [original project](https://code.google.com/archive/p/moshpytt/downloads) is unmaintained.

I don't know your exact use case, but in general I would suggest that you use the [tesstrain.sh](https://github.com/tesseract-ocr/tesseract/wiki/tesstrain.sh) script to do your training; it is much faster and more accurate than manually editing box files.

**Comment by cantrowitz** [comment]
Thanks!
