### ISSUE TITLE
Navigation 

### ISSUE THREAD

**Issue by RanyAlbegWein** [ddohler/moshpytt#3]
**_Hi ddohler,_**

It might not be an issue but I find no other way to contact you.
First of all many thanks for your moshPyTT improvements!

Second, unfortunately I'm unable to move the boxes down - Num8 and Num2 **both** shifts up a rectangle.
Is it actually an issue or am I missing something?

**UPDATE**: Saw that this is indeed an issue.
The fix is:
```
elif direction == 'BOTTOM':
    self.top -= step
    self.bottom -= step
```

Instead of 

```
elif direction == 'BOTTOM':
    self.top += step
    self.bottom += step
```

Thanks!

**Comment by ddohler** [comment]
Hi, I haven't worked with this program for a long time, so I might be forgetting something, but the logic for the key presses is here: https://github.com/ddohler/moshpytt/blob/master/moshpytt.py#L429

Looking at that code, it looks like the arrow keys can also work for moving, have you tried using the arrow keys instead of the number pad? 

Also, I just wanted to check, are you sure you need to manually edit box files? The newest versions of tesseract come with scripts that can automatically generate boxfiles for training so that you don't need to edit them yourself.

Hope that helps!

**Comment by RanyAlbegWein** [comment]
Thank you very much for the quick response!
I updated my question to include a simple fix to _moshpytt.py_.

> Also, I just wanted to check, are you sure you need to manually edit box files? The newest versions of tesseract come with scripts that can automatically generate boxfiles for training so that you don't need to edit them yourself.

That is interesting, could you please elaborate a bit more about these scripts, or direct me to a source from which I'll be able to learn about the process?

Thank you! :-)

Rany.

**Comment by ddohler** [comment]
Thanks for the fix! I'll try and add that soon. 

About automatic training, take a look at https://github.com/tesseract-ocr/tesseract/blob/master/training/tesstrain.sh and see if that helps. Good luck!

**Comment by ddohler** [comment]
Rany, thanks again for the fix -- I've pushed up your changes to master so this can be closed.

**Comment by RanyAlbegWein** [comment]
Cool :-) Thank you for sharing helpful content on GitHub!
